show databases;
create database trial;
use trial;
show tables;
create table patient(id int,ht int,wt int,med_history varchar(50),foreign key(id) references person(id));
create table doctor(id int,lic_no int,reg_no int,experience int,degree varchar(30),spltion varchar(30),timing varchar(30),fee int);
create table person(id int auto_increment,prof varchar(11),usrname varchar(25),addr varchar(30),emailid varchar(30),id_p int(13),gender varchar(10),dob date,phno int,pswd1 varchar(25),pswd2 varchar(25),primary key(id));
create table receptionist(id int,wrk_hrs int,salary float);
create table appoint(id int,usrname varchar(25),doctor varchar(25),gender varchar(25),phnno int,emailid varchar(30),v_dt date,v_time varchar(20));
select * from person;
drop table person;